server:

  aws:
    default:
      region: "sa-east-1"
    credentials-factory: kikaha.cloud.aws.iam.AmazonCredentialsFactory$Yml
    iam-policy:
      access-key-id: *****ACESSKEY*****
      secret-access-key: *****SECRETKEY*****

  static: { enabled: true, webjar-enabled: true }

  Access-Control-Allow-Credentials: true

  urouting:
    default-content-type: "application/json"

  websocket:
    default-serializer: "application/json"
    default-unserializer: "application/json"

  smart-routes:
    auth:
      login-form-enabled: false
      logout-url-enabled: true
      logout-http-method: "POST"
    cors:
      enabled: true
      always-allow-origin: true
      always-allow-credentials: true
      allowed-methods: [ "GET", "PUT", "POST", "DELETE", "PATCH" ]

  db:
    datasources:
      default:
        jdbc-url: "jdbc:mysql://guismi.ctebgduzcfr5.sa-east-1.rds.amazonaws.com/guism?serverTimezone=UTC"
        username: "guismiADM"
        password: "*****"
        useSSL: "true"
        verifyServerCertificate: "true"
        requireSSL: "false"
        log-query-execution-longer-than-ms: -1

  auth:
    session-store: kikaha.core.modules.security.InMemorySessionStore
    
    endpoints:
      permission-denied-page: "/forbidden.html"
      callback-url: "/api/auth/callback"
      logout-url: "/api/auth/logout"
      login-page: "/"

    db-auth:
      select-user-password: "select senha as password  from jogador where login = ?"
      select-user-roles: "select role from jogador where login = ?"

    rules:
      - { pattern: "/api/*", auth-mechanisms: [ "basic", "json" ], identity-managers: [ "db-auth" ] }
      - { pattern: "/*", auth-mechanisms: [ "basic", "form" ], identity-managers: [ "db-auth" ] }
    default-excluded-patterns: [ "/static/*"]

  http:
    enabled: true
    host: "0.0.0.0"
    port: 80
