server:

  static: { enabled: true, webjar-enabled: true }

  Access-Control-Allow-Credentials: true

  urouting:
    default-content-type: "application/json"

  websocket:
    default-serializer: "application/json"
    default-unserializer: "application/json"

  smart-routes:
    auth:
      login-form-enabled: false
      logout-url-enabled: true
      logout-http-method: "POST"

  db:
    datasources:
      default:
        jdbc-url: "jdbc:mysql://guismi.ctebgduzcfr5.sa-east-1.rds.amazonaws.com/guism?serverTimezone=UTC"
        username: "guismiADM"
        password: "karen#GOD"
        useSSL: "true"
        verifyServerCertificate: "true"
        requireSSL: "false"
        log-query-execution-longer-than-ms: -1

  auth:
    session-store: kikaha.core.modules.security.InMemorySessionStore

  http:
    enabled: true
    host: "0.0.0.0"
    port: 9000
